### ISSUE TITLE
mod_rst.c:653 no enough parameters,but continue!

### ISSUE THREAD

**Issue by asoldasdino** [nwaycn/rst#3]
Hello!
I'm trying to use the module like this:
Dialplan command: 
action application="rst" data="172.1.1.11 3001"

Whatever I place as data it always says:
2023-10-23 14:12:29.279383 [ERR] mod_rst.c:653 no enough parameters, but continue!
in the cli and sends data to the defaults (to what's set in the file)
What am I doing wrong?

FreeSWITCH (Version 1.6.20  64bit)

**Comment by nwaycn** [comment]
`<action application="set" data="execute_on_answer='rst serverip serverport'"/>   `
if you use fs 1.10.x, can use 

`<action application="set" data="execute_on_answer=rst serverip serverport"/>`

This application like record_session ,not record 
![image](https://github.com/nwaycn/rst/assets/10083564/4b70071b-4edb-4ae1-8bff-7b164f9e2fb6)
