### ISSUE TITLE
语音流格式

### ISSUE THREAD

**Issue by zhmi19811015** [nwaycn/rst#5]
![0000](https://github.com/nwaycn/rst/assets/35604653/71e05f02-be24-4e2e-9fb5-a05bf556efed)
我使用wireshark 出现的是乱码，请问这里的数据流是什么样的字符编码？
我如果用java-netty如何解析？
这个数据流是采样率是8K吗

mod_rst中makefile文件git冲突，编译失败
![1111](https://github.com/nwaycn/rst/assets/35604653/0fd217fd-0514-4caf-9a45-41413cb95364)

**Comment by nwaycn** [comment]
后来没有太关注这个项目，你可以把以前的Makefile恢复看看编译，传送的语音流是 pcma/pcmu/l16
